name: pigami
version: '1.0'
summary: A rolling block adventure.
description: |
  The principle, roll your cube (rather rectangular) to reach the finish without falling!
  Buttons, Traps and other objects are there to make the game more challenging.
  For the more experienced, the game has a level generator. The algorithm used will put your intelligence to the test.

icon: "./resources/favicon.png"
grade: stable
confinement: strict
base: core18

apps:
  pigami:
    command: desktop-launch ${SNAP}/bin/pigami
    plugs:
    - audio-playback
    - opengl
    - x11
    - pulseaudio

parts:

  desktop-glib-only:
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    build-packages:
    - libglib2.0-dev
    stage-packages:
    - libglib2.0-bin

  pigami:
    after:
    - desktop-glib-only
    plugin: cmake
    build-snaps: [cmake/latest/edge] # We need cmake >= 3.11
    source: https://github.com/ArthurSonzogni/pigami
    source-type: git
    source-depth: 1
    stage-packages:
    - libgl1-mesa-glx
    - libpulse0
    build-packages:
    - libglu-dev
    - libpulse-dev
    - xorg-dev
    override-build: |
      /snap/bin/cmake \
        -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_PART_INSTALL \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        $SNAPCRAFT_PART_SRC
      make -j ${SNAPCRAFT_PARALLEL_BUILD_COUNT}
      make install

passthrough:
  title: pigami
  license: MIT
