name: pigami
adopt-info: pigami
summary: A rolling block adventure.
description: |
  The principle, roll your cube (rather rectangular) to reach the finish without falling!
  Buttons, Traps and other objects are there to make the game more challenging.
  For the more experienced, the game has a level generator. The algorithm used will put your intelligence to the test.

icon: "./resources/favicon.png"
grade: stable
confinement: strict
base: core20

apps:
  pigami:
    command: bin/desktop-launch $SNAP/usr/bin/pigami
    plugs:
    - audio-playback
    - opengl
    - x11
    - pulseaudio

parts:

  desktop-glib-only:
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    build-packages:
    - libglib2.0-dev
    stage-packages:
    - libglib2.0-bin

  pigami:
    after:
    - desktop-glib-only
    plugin: cmake
    source: https://github.com/ArthurSonzogni/pigami
    source-type: git
    stage-packages:
      - libgl1-mesa-glx
      - libopengl0
      - libpulse0
    build-packages:
      - libglu1-mesa-dev
      - libpulse-dev
      - xorg-dev
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git rev-list --count HEAD)
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release

passthrough:
  title: pigami
  license: MIT
